# Generated by Django 4.2.3 on 2024-01-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteartist',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='voteartist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='votetrack',
            name='track',
        ),
        migrations.RemoveField(
            model_name='votetrack',
            name='user',
        ),
        migrations.DeleteModel(
            name='VoteAlbum',
        ),
        migrations.DeleteModel(
            name='VoteArtist',
        ),
        migrations.DeleteModel(
            name='VoteTrack',
        ),
    ]
