# Generated by Django 4.2.3 on 2024-01-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('zipcode', models.CharField(max_length=255, verbose_name='Имя')),
                ('peopleNumbers', models.IntegerField(verbose_name='Населенность')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ManyToManyField(to='users.city', verbose_name='Город проживания'),
        ),
    ]
