# Generated by Django 4.2.3 on 2024-01-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_city_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='zipcode',
            field=models.CharField(max_length=255, verbose_name='ЗИП КОД'),
        ),
    ]
