# Generated by Django 4.2.3 on 2024-01-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_city_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tastes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Жанр')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='tastes',
            field=models.ManyToManyField(to='users.tastes', verbose_name='Город проживания'),
        ),
    ]
