# Generated by Django 4.2.3 on 2024-01-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
