# Generated by Django 4.2.3 on 2024-01-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_alter_artist_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('receive_adv', models.BooleanField(verbose_name='Получать рекламу')),
            ],
        ),
    ]
