# Generated by Django 4.2.3 on 2024-01-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_subscribeform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribeform',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='subscribeform',
            name='phone',
            field=models.CharField(max_length=255, unique=True, verbose_name='Телефон'),
        ),
    ]
