# Generated by Django 4.2.3 on 2024-01-07 11:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_alter_subscribeform_email_alter_subscribeform_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribeform',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True, verbose_name='Телефон'),
        ),
    ]
